### ISSUE TITLE
Permissions

### ISSUE THREAD

**Issue by MatteoPiovanelli-Laser** [bleroy/Nwazet.Commerce#100]
I would set more granular permissions, to give more flexibility.

e.g. regarding the `ManageCommerce` permission, I would have it imply:
- a `ManageProducts` permission
- a `ManageAttributes` permission
- a `ManagePromotions` permission
- a `ManageReports` permission
and so on...

The idea is that there could be several people accessing the abckend, all with a specific job:
e.g. people from marketing may need to see reports and handle promotions, but not add/edit products. Someone may be responsible for adding products to the catalog, but they should not be allowed to change tax settings...

The `ManageCommerce` permission would remain as it is, and grant all rights and be used for cases where there is a single person taking care of everything. The other permissions would allow flexibility for larger organizations.

**Comment by bleroy** [comment]
This sounds like a good feature. +1
