### ISSUE TITLE
Localization of Products and Bundles

### ISSUE THREAD

**Issue by MatteoPiovanelli-Laser** [bleroy/Nwazet.Commerce#114]
Continuation of #99 #101 #110.

Like I did for ProductAttributes, I am planning to do a feature that allows similar automatic behaviours in the relationship in place between products and bundles. Again, there would be settings at the level of ContentTypeDefinition, for BundleParts, to set up the synchronization and validation options.

Again, the idea is to enable support to multiple cultures in an easy-to-manage way.

**Comment by bleroy** [comment]
Sounds great. Bundles are quite complicated to handle, but they are a necessity.

**Comment by MatteoPiovanelli-Laser** [comment]
Thanks for merging. I am closing this issue now.
