### ISSUE TITLE
.orig files

### ISSUE THREAD

**Issue by MatteoPiovanelli-Laser** [bleroy/Nwazet.Commerce#137]
Drivers/ProductPartDriver.cs.orig
Migrations/CommerceMigrations.cs.orig
Models/ProductPart.cs.orig
Models/ProductPartRecord.cs.orig

THese files are in the repository. I noticed them by checking all non-source-code files in the folders before a deploy.

I would say we should remove them, because I am not aware of a reason to keep them.

**Comment by bleroy** [comment]
They shouldn't be there. That's a mistake. thanks.

**Comment by MatteoPiovanelli-Laser** [comment]
I will get rid of those in the PR I'll make for the Territories. Hopefully I'll be able to get back to work on that today or tomorrow

**Comment by MatteoPiovanelli-Laser** [comment]
I'll close this issue because those files were removed from the repo in #140
