### ISSUE TITLE
ArgumentNullException in WishLists

### ISSUE THREAD

**Issue by MatteoPiovanelli-Laser** [bleroy/Nwazet.Commerce#138]
ProductPartWishListDriver.Display calls _wishListsUIServices.CreateShape(user, part) even when the user is null. THe idea is that there should be an "Add to list" link even for non-authenticated users, even if wishlists require an authenticated user. 
The implementation of CreateShape throws ArgumentNullException on user==null. This should probably be change to avoid filling up the logs with errors when this is really a normal situation

**Comment by bleroy** [comment]
It should probably have some configurable behavior, the default being to redirect you to authentication/account creation. Other options could be to redirect somewhere, or to create some form of list in client storage... Now that could be costly, but on the other hand, I thought that was somehow the plan all along. Maybe I got that wrong, but would that make sense?

**Comment by MatteoPiovanelli-Laser** [comment]
I think that was the point of having the IWishListsUIServices separate, yes. That way one would only have to write the two methods for those shapes to do the different things. I think throwing this exception is a leftover from initially trying to use these methods for something else.

**Comment by MatteoPiovanelli-Laser** [comment]
Also IWishListExtensionProvider  is there for further customizations
