### ISSUE TITLE
Web site template of nwazet.commerce eshop

### ISSUE THREAD

**Issue by giannik** [bleroy/Nwazet.Commerce#146]
Hello. 
Is the nwazet eshop theme with sample products as shown here (https://www.youtube.com/watch?v=fyK4vDEOb8o) available for download ? 
I would to use it as starting point for an orchard e-shop.
Thank you.

**Comment by bleroy** [comment]
It's not. It contains some branding that would require some scrubbing. I should probably do that at some point, but in the meantime, I can share it with you privately. Send me an email at bertrandleroy at gmail.
