### ISSUE TITLE
Product attributes don't export nicely

### ISSUE THREAD

**Issue by bleroy** [bleroy/Nwazet.Commerce#53]
Originally reported by: **Bertrand Le Roy (Bitbucket: [bleroy](http://bitbucket.org/bleroy), GitHub: [bleroy](http://github.com/bleroy))**

---

They lack a proper id.

---
- Bitbucket: https://bitbucket.org/bleroy/nwazet.commerce/issue/53

**Comment by MatteoPiovanelli-Laser** [comment]
OK if I add a GUID?

**Comment by bleroy** [comment]
I really dislike GUIDs. I'd prefer if we could explore other possibilities. For instance, we could add a technical name for attributes, and generate that from its display name if it's not explicitly provided. What do you think?

**Comment by MatteoPiovanelli-Laser** [comment]
I agree that GUIDs are less than ideal in most cases.
I will give a look at how the AutoRoutePart in Orchard generates and uses the DisplayAlias (not sure this is the name of the property) and get back to you on this. I am wondering if there is a way to throw some information form the Attribute values in it as well.

**Comment by MatteoPiovanelli-Laser** [comment]
The way I am implementing this right now, the technical name is part of an attribute's Identity, and is generated similarly to the way the technical name for Fields is generated during a ContentType's definition.
Still have to implement the actual Import/export logic for ProductAttributePart and ProductAttributesPart

**Comment by MatteoPiovanelli-Laser** [comment]
In Exporting/Importing ProductAttributesPart, should I keep the "Ids" attribute for retrocompatibility?
My idea is I'll keep it in `Exporting`, and consider it in `Importing` only if the new attribute that uses the TechnicalNames as identities is not there.

**Comment by bleroy** [comment]
No, ids should never make it to an export. Retrocompatibility is not that important for import/export, as those are not designed to be long-lived and there's no promise of back compat with them.
