### ISSUE TITLE
Product add button fails to render when associated attribute is deleted

### ISSUE THREAD

**Issue by bleroy** [bleroy/Nwazet.Commerce#58]
Originally reported by: **Josh Berry (Bitbucket: [joshberry](http://bitbucket.org/joshberry), GitHub: [joshberry](http://github.com/joshberry))**

---

When an attribute that was previously associated with a product is deleted, the add button for that product no longer displays. This is caused by an exception thrown from the GetAttributes method in ProductAttributeService.

This is not intuitive and cumbersome for users as they have to go into each product the deleted attribute was associated with and re-save it to resolve the issue.

Steps to repro:
1. Create a new attribute
2. Associate the attribute with a product
3. Delete the attribute created in step 1
4. View the product - the add button is missing

---
- Bitbucket: https://bitbucket.org/bleroy/nwazet.commerce/issue/58

**Comment by MatteoPiovanelli-Laser** [comment]
Hi. Adding to this, there is a further issue with removing attributes.

1. Create 2 attributes.
2. Associate them both with a product.
3. Delete one attribute.
4. View the product: both the "add to cart" button and the dropdown for the second attribute are missing.
