### ISSUE TITLE
Index for Sku?

### ISSUE THREAD

**Issue by bleroy** [bleroy/Nwazet.Commerce#72]
Originally reported by: **Dieter Schüle (Bitbucket: [dpomt](http://bitbucket.org/dpomt), GitHub: [dpomt](http://github.com/dpomt))**

---

Hello Bertrand,

since I have changed Sku to be identity for ProductPart - would it make sense to add a index for Sku in Migrations?

---
- Bitbucket: https://bitbucket.org/bleroy/nwazet.commerce/issue/70

**Comment by MatteoPiovanelli-Laser** [comment]
Looks like what is proposed here is already done. @bleroy, would you close this issue?
