### ISSUE TITLE
Current source not work in 1.9.1

### ISSUE THREAD

**Issue by bleroy** [bleroy/Nwazet.Commerce#80]
Originally reported by: **apolun (Bitbucket: [apolun](http://bitbucket.org/apolun), GitHub: [apolun](http://github.com/apolun))**

----------------------------------------

Hi
I Fork this commerce to test for future work and customization 
but unfortunately my clone is not shown in admin menu 
There are two message shown in log :
1-  Orchard.Environment.Extensions.ExtensionManager - No suitable loader found for extension "Nwazet.Commerce"
2- The type or namespace name 'UsedImplicitly' could not be found (are you missing a using directive or an assembly reference?) on ProductAttributesPartDriver line 97

----------------------------------------
- Bitbucket: https://bitbucket.org/bleroy/nwazet.commerce/issue/78

**Comment by attilah** [comment]
I think you can close this, since I've removed JetBrains in the nuget fix.
