### ISSUE TITLE
Double is unsuitable data type for price

### ISSUE THREAD

**Issue by armanforghani** [bleroy/Nwazet.Commerce#86]
I think we should change data type of price fields to decimal because double is not good choice to work with money.
There are several references for that.

http://stackoverflow.com/questions/316727/is-a-double-really-unsuitable-for-money
http://stackoverflow.com/questions/1165761/decimal-vs-double-which-one-should-i-use-and-when

**Comment by bleroy** [comment]
ok

**Comment by MatteoPiovanelli-Laser** [comment]
I am looking into this.
A lot of interfaces will change, breaking things.

**Comment by MatteoPiovanelli-Laser** [comment]
I am having issues with the migrations for this. See the issue I opened in the Orchard repo https://github.com/OrchardCMS/Orchard/issues/7615.

The table is `ProductPartRecord`. The column `DiscountPrice`

I think I was able to change every other price to decimal, but I cannot seem to find how to fix the table there.

**Comment by armanforghani** [comment]
Great work. Thank you all so much.

**Comment by MatteoPiovanelli-Laser** [comment]
Not a problem.

@armanforghani would you share the url of any ecommerce you have live that uses Nwazet? I am curious as to what everyone else is using it for.
